"use client";

import { Quotation } from "@/redux/features/quotation/quotationSlice";
import React, { FormEvent, useState } from "react";
import { affirmaPDF } from "../quotation/affirmaPDFHelper";

const CreateProductPage = () => {
  const [quotationState, setQuotationState] = useState<Quotation>({
    quotationSequal: "withDummy",
    agent: "affirma",
    supportingDoc: true,
    markup: 0,
    fileFormat: "",
    quoteNo: {
      noAffirmaQuote: undefined,
      noInnosysQuote: undefined,
      noBiomechQuote: undefined,
    },
    loading: false,
    errors: {
      customer: "No Customer Selected",
      organization: "No Organization Selected",
    },
    quotationHeaders: {
      affirma: {
        id: "",
        agent: "affirma",
        quotationType: "",
        quotationRef: "qt2025-01203",
        date: new Date(Date.now()).toISOString().split("T")[0],
        customer: {
          title: "sr",
          fullname: "melinda",
        },
        title: "Hello",
        selectedOrganization: {
          id: "",
          department: "cssd",
          organizationName: "hospital sultanah aminah",
          organizationSSMNo: "",
          organizationTINNo: "",
          addressLine1: "jalan persiaran abu bakar sultan",
          addressLine2: "",
          addressLine3: "",
          postcode: "80100",
          city: "johor bahru",
          province: "johor",
          country: "malaysia",
        },
      },
      innosys: {
        id: "",
        agent: "affirma",
        quotationType: "",
        quotationRef: "qt2025-01203",
        date: new Date(Date.now()).toISOString().split("T")[0],
        customer: {
          title: "sr",
          fullname: "melinda",
        },
        title: "Hello",
        selectedOrganization: {
          id: "",
          department: "cssd",
          organizationName: "hospital sultanah aminah",
          organizationSSMNo: "",
          organizationTINNo: "",
          addressLine1: "jalan persiaran abu bakar sultan",
          addressLine2: "",
          addressLine3: "",
          postcode: "80100",
          city: "johor bahru",
          province: "johor",
          country: "malaysia",
        },
      },
      biomech: {
        id: "",
        agent: "affirma",
        quotationType: "",
        quotationRef: "qt2025-01203",
        date: new Date(Date.now()).toISOString().split("T")[0],
        customer: {
          title: "sr",
          fullname: "melinda",
        },
        title: "Hello",
        selectedOrganization: {
          id: "",
          department: "cssd",
          organizationName: "hospital sultanah aminah",
          organizationSSMNo: "",
          organizationTINNo: "",
          addressLine1: "jalan persiaran abu bakar sultan",
          addressLine2: "",
          addressLine3: "",
          postcode: "80100",
          city: "johor bahru",
          province: "johor",
          country: "malaysia",
        },
      },
    },

    quotationItems: {
      affirma: [
        {
          no: "1",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "2",
          id: "",
          sku: "",
          productCode: "77.11.10",
          description: 'Hohmann bone lever, 10mm, s/steel,  220mm, 8 3/4"',
          qty: 1,
          oum: "pc",
          unitPrice: 529,
          totalPrice: 529,
          productImage: "",
        },
        {
          no: "3",
          id: "",
          sku: "",
          productCode: "03.50.14",
          description:
            'Operating scissors, sharp/sharp, curved, s/steel, 145mm, 5 3/4"',
          qty: 5,
          oum: "pc",
          unitPrice: 157,
          totalPrice: 562,
          productImage: "",
        },
        {
          no: "4",
          id: "",
          sku: "",
          productCode: "C-000.32.355",
          description:
            "HR Binocular loupes 2.5X/340mm, S-Frame with i-View, detachable protective lenses, 2 sterilisable swivel levers, retaining cord, cleaning fluid and carrying case.",
          qty: 2,
          oum: "pc",
          unitPrice: 6550,
          totalPrice: 13100,
          productImage: "",
        },
        {
          no: "5",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "6",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "7",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "8",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "9",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "10",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "11",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "12",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "13",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "14",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "15",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "16",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "17",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "18",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "19",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "20",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "21",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "22",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "23",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "24",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "25",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
      ],
      innosys: [
        {
          no: "1",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "2",
          id: "",
          sku: "",
          productCode: "77.11.10",
          description: 'Hohmann bone lever, 10mm, s/steel,  220mm, 8 3/4"',
          qty: 1,
          oum: "pc",
          unitPrice: 529,
          totalPrice: 529,
          productImage: "",
        },
        {
          no: "3",
          id: "",
          sku: "",
          productCode: "03.50.14",
          description:
            'Operating scissors, sharp/sharp, curved, s/steel, 145mm, 5 3/4"',
          qty: 5,
          oum: "pc",
          unitPrice: 157,
          totalPrice: 562,
          productImage: "",
        },
        {
          no: "4",
          id: "",
          sku: "",
          productCode: "C-000.32.355",
          description:
            "HR Binocular loupes 2.5X/340mm, S-Frame with i-View, detachable protective lenses, 2 sterilisable swivel levers, retaining cord, cleaning fluid and carrying case.",
          qty: 2,
          oum: "pc",
          unitPrice: 6550,
          totalPrice: 13100,
          productImage: "",
        },
        {
          no: "5",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "6",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "7",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "8",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "9",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "10",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "11",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "12",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "13",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "14",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "15",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "16",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "17",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "18",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "19",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "20",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "21",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "22",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "23",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "24",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "25",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
      ],
      biomech: [
        {
          no: "1",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "2",
          id: "",
          sku: "",
          productCode: "77.11.10",
          description: 'Hohmann bone lever, 10mm, s/steel,  220mm, 8 3/4"',
          qty: 1,
          oum: "pc",
          unitPrice: 529,
          totalPrice: 529,
          productImage: "",
        },
        {
          no: "3",
          id: "",
          sku: "",
          productCode: "03.50.14",
          description:
            'Operating scissors, sharp/sharp, curved, s/steel, 145mm, 5 3/4"',
          qty: 5,
          oum: "pc",
          unitPrice: 157,
          totalPrice: 562,
          productImage: "",
        },
        {
          no: "4",
          id: "",
          sku: "",
          productCode: "C-000.32.355",
          description:
            "HR Binocular loupes 2.5X/340mm, S-Frame with i-View, detachable protective lenses, 2 sterilisable swivel levers, retaining cord, cleaning fluid and carrying case.",
          qty: 2,
          oum: "pc",
          unitPrice: 6550,
          totalPrice: 13100,
          productImage: "",
        },
        {
          no: "5",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "6",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "7",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "8",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "9",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "10",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "11",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "12",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "13",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "14",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "15",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "16",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "17",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "18",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "19",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "20",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "21",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "22",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "23",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "24",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
        {
          no: "25",
          id: "",
          sku: "",
          productCode: "78.00.20",
          description:
            "Funke hand fixation plate for individual and variable fixation, teflon autoclavable 255x240x8mm",
          qty: 10,
          oum: "pc",
          unitPrice: 2620,
          totalPrice: 26200,
          productImage: "",
        },
      ],
    },
  });

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    await affirmaPDF(quotationState);
  };

  return (
    <form onSubmit={handleSubmit}>
      <button type="submit" className="bg-amber-600 rounded-md px-5 py-2">
        Create Quotation
      </button>
    </form>
  );
};

export default CreateProductPage;
